baseURL = "https://1000.tocotronic.ru/"
buildDrafts = true
canonifyURLs = true
languageCode = "ru-ru"
publishdir = "public"
theme = "hugo-theme-bleak"
title = "1000 и 1 альбом"
[author]
homepage = "http://khabaroff.com"
name = "Sergey Khabaroff"
[params]
cover = "/images/cover.jpg"
description = "Я люблю свои пластинки больше, чем тебя"
disqus = "xxxxxxxxx"
domainverification = "xxxxxxxxxxxxxxxxxxxxx"
googleanalyticsuserid = "UA-xxxxxxxx-x"
subtitle = "Я люблю свои пластинки больше, чем тебя"
[params.author]
facebook = "https://www.facebook.com/khabaroff"
firstname = "Sergey"
gender = "Male"
github = "https://github.com/khabaroff"
gplus = "https://plus.google.com/+SergeyKhabaroff"
gravatarhash = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
image = "//www.gravatar.com/avatar/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.png"
lastname = "Khabaroff"
linkedin = "https://www.linkedin.com/in/khabaroff/"
twitter = "https://twitter.com/khabaroff"
username = "khabaroff"
website = "https://khabaroff.com/"
[taxonomies]
category = "categories"
tag = "tags"

#hugo --theme=hugo-theme-bleak --buildDrafts --baseURL="http://1000.dev/"