baseURL = "https://khabaroff.com/1000/"
buildDrafts = false
canonifyURLs = true
languageCode = "ru-ru"
publishdir = "public"
theme = "hugo-theme-bleak"
title = "1000 и 1 альбом"
[author]
homepage = "http://khabaroff.com"
name = "Sergey Khabaroff"
[[menu.main]]
name = "О проекте"
url = "/page/about/"
weight = 2
[[menu.main]]
name = "Главная"
url = "/"
weight = 1
[[menu.main]]
name = "Оценки проекта"
url = "/page/rated/"
weight = 8
[[menu.main]]
name = "Теги проекта"
url = "/page/tags/"
weight = 7
[params]
cover = "img/share.jpg"
description = "Я люблю свои пластинки больше, чем тебя"
disqus = "khabaroff"
site_description = "Я люблю свои пластинки больше, чем тебя"
subtitle = "Я люблю свои пластинки больше, чем тебя"
[params.author]
email = "khabaroff@gmail.com"
facebook = "https://www.facebook.com/khabaroff"
facebook_app_id = "211990835519735"
firstname = "Sergey"
github = "https://github.com/khabaroff"
gplus = "https://plus.google.com/+SergeyKhabaroff"
image = "https://khabaroff.com/1000/img/share.jpg"
lastname = "Khabaroff"
linkedin = "https://www.linkedin.com/in/khabaroff/"
twitter = "khabaroff"
username = "khabaroff"
website = "https://khabaroff.com/"
[taxonomies]
category = "rated"
tag = "tags"
